/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"


void
opr_prog_1(char *host,int x)
{
	CLIENT *clnt;
	num  *result_1;
	numbers  opr_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OPR_PROG, OPR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	opr_1_arg.a=x;
	result_1 = opr_1(&opr_1_arg, clnt);
	if (result_1 == (num *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		int i=0;
		for(i=0;i<x;i++)
		{
			printf("%d\n",result_1->array[i])
			
			
			
			
			
			;
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	opr_prog_1 (host,atoi(argv[2]));
exit (0);
}
