/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"
#include<stdbool.h> 

int *
isprime_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("isPrime(%d) is called\n",argp->n);
	int i = 1;
	bool prime = TRUE;
	while(i == (argp->n)/2) {
		if((argp->n)/i == 0) {
			prime = FALSE;
		}
	}
    if(prime) {
		result = 1;
		printf("\n given number is prime\n");
	} else {
		result = 0;
		printf("\n given number is not prime\n");
	}
	return &result;
}
