/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIME_H_RPCGEN
#define _PRIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct number {
	int n;
};
typedef struct number number;

#define PRIME_PROG 0x4562877
#define PRIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define isPrime 1
extern  int * isprime_1(number *, CLIENT *);
extern  int * isprime_1_svc(number *, struct svc_req *);
extern int prime_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define isPrime 1
extern  int * isprime_1();
extern  int * isprime_1_svc();
extern int prime_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_number (XDR *, number*);

#else /* K&R C */
extern bool_t xdr_number ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIME_H_RPCGEN */
